#! /bin/bash -l
#Initialise time solat incase Jakim solat time fails
# This file is placed in /etc/cron.daily and change the mode to +x
# Created by Aminudin Afip @ amin.afip@gmail.com 14 Apr 2020
SUBUH="6:18"
ZOHOR="13:30"
ASAR="16:47"
MAGHRIB="19:29"
ISYA="20:39"


#Get solat time from Jakim
my_array=($(lynx -dump https://www.e-solat.gov.my/index.php?r=esolatApi/xmlfeed\&zon=SGR01|\
cut --complement -d "," -f 1,3,4|\
grep -v H.S|cut --complement -d "M" -f 1))

#Test solat Jakim whether ok or not, otherwise set default
if [ -z "${my_array[3]}" ]; then
   echo " Subuh kosong"

   my_array[8]=$SUBUH
   my_array[10]=$ZOHOR
   my_array[12]=$MAGHRIB
   my_array[13]=$ISYA

  echo "Subuh ${my_array[8]:0:5}"
  echo "Zohor ${my_array[10]:0:5}"
  echo "Maghrib ${my_array[12]:0:5}"
fi




# This section will create a text file in /home/pi directory as a time format - 
# means delay by, the rest is time in future
# Bahagian ini untuk buat file untuk store waktu


arrayLen=${#my_array[@]}
arrayWaq=("Imsak" "Subuh" "Syuruk" "Zuhur" "Asar" "Maghrib" "Isyak")
echo "${my_array[8]:0:5}" > /home/pi/subuh
echo "${my_array[10]:0:5}" > /home/pi/zohor
echo "${my_array[12]:0:5}" > /home/pi/maghrib
echo "${my_array[13]:0:5}" > /home/pi/isya
echo "$(date +"%d-%m-%y")" > /home/pi/harini
date -d "1 days " +"%d-%m-%y" > /home/pi/esok
date -d "${my_array[10]:0:5} today - 5 minutes" +"%H:%M" > /home/pi/ONpreZohor5m
date -d "${my_array[10]:0:5} 35 minutes" +"%H:%M" > /home/pi/ONzohor30m
date -d "${my_array[8]:0:5} 29 minutes" +"%H:%M" > /home/pi/ONsubuh29m
date -d "${my_array[8]:0:5} 31 minutes" +"%H:%M" > /home/pi/ONsubuh32m
date -d "${my_array[8]:0:5} 102 minutes" +"%H:%M" > /home/pi/OFFsubuh
date -d "${my_array[12]:0:5} 29 minutes" +"%H:%M" > /home/pi/ONmaghrib29m
date -d "${my_array[12]:0:5} 32 minutes" +"%H:%M" > /home/pi/ONmaghrib30m
date -d "${my_array[12]:0:5} 115 minutes" +"%H:%M" > /home/pi/OFFmaghrib
date -d "${my_array[10]:0:5} 0 minutes" +"%H:%M" > /home/pi/MimbarSolat2m
date -d "${my_array[10]:0:5} 9 minutes" +"%H:%M" > /home/pi/MimbarJmt10m
date -d "${my_array[10]:0:5} 30 minutes" +"%H:%M" > /home/pi/MimbarSolat30m
date -d "${my_array[10]:0:5} 30 minutes" +"%H:%M" > /home/pi/MimbarSolat33m


# TAzkirah Jumaat hardcoded /home/pi/Tazkirah
# Mail Maghrib
# This section shows how to use the file generated above in the script


#echo "Kul Maghrib $(</home/pi/harini) - ON  $(</home/pi/ONmaghrib29m) dan OFF  $(</home/pi/OFFmaghrib)" > /home/pi/mailMagh-sub
# echo "Pastikan sonoff - ON  $(</home/pi/ONmaghrib29m) dan OFF  $(</home/pi/OFFmaghrib)" > /home/pi/mailMagh-body
# MAil Subuh 
#echo "Kul Subuh $(</home/pi/esok) - ON  $(</home/pi/ONsubuh30m) dan OFF  $(</home/pi/OFFsubuh)" > /home/pi/mailSubuh-sub
#echo "Pastikan sonoff - ON  $(</home/pi/ONsubuh30m) dan OFF  $(</home/pi/OFFsubuh)" > /home/pi/mailSubuh-body
